/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quis1;

import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO SLIM 3 R3
 */
public class Quiz1pemvis extends javax.swing.JFrame {
    private Integer totalHarga;
    

    /**
     * Creates new form Quiz1pemvis
     */
    public Quiz1pemvis() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fJenis = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        fJumlah = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lKopi = new javax.swing.JLabel();
        lHarga = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bHapus = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        bTambah = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fKetjumlah = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        fTotal = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("KOPI JAVVA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 195, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Jenis Kopi           :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        fJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Kopi", "Arabica Coffee", "Robusta Coffee", "Liberian Coffee", "Excelsa Coffee" }));
        fJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fJenisActionPerformed(evt);
            }
        });
        jPanel1.add(fJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 195, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Jumlah Pesanan :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        fJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fJumlahActionPerformed(evt);
            }
        });
        jPanel1.add(fJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 195, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Kopi");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Harga");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        lKopi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lKopi.setText("Jenis kopi yang dipilih");
        jPanel1.add(lKopi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 200, -1));

        lHarga.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lHarga.setText("Harga ");
        jPanel1.add(lHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Total");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        bHapus.setBackground(new java.awt.Color(153, 102, 0));
        bHapus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bHapus.setForeground(new java.awt.Color(255, 255, 255));
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        jPanel1.add(bHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 170, 40));

        bKeluar.setBackground(new java.awt.Color(153, 102, 0));
        bKeluar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bKeluar.setForeground(new java.awt.Color(255, 255, 255));
        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(bKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 170, 40));

        bTambah.setBackground(new java.awt.Color(153, 102, 0));
        bTambah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTambah.setForeground(new java.awt.Color(255, 255, 255));
        bTambah.setText("Tambahkan");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });
        jPanel1.add(bTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 350, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("===============================");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 420, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Jumlah");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        fKetjumlah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fKetjumlah.setText("Jumlah yang dibeli");
        jPanel1.add(fKetjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quis1/coffee-cup-removebg-preview-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, 150, 160));

        jLabel13.setText("Kopi no 1 di Indonesia");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 360, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("===============================");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 420, -1));

        fTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fTotal.setText("Total Harga");
        jPanel1.add(fTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quis1/bg kopi 2.jpg"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, -10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        lKopi.setText("");
        lHarga.setText("");
        fKetjumlah.setText("");
        fJenis.setSelectedItem("Pilih Jenis Kopi");
        fJumlah.setText("");
        fTotal.setText("");
    }//GEN-LAST:event_bHapusActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        // TODO add your handling code here:
        String item = fJenis.getSelectedItem().toString();
        String jumlah = fJumlah.getText();
        Integer harga = null;
        if(item.equals("Arabica Coffee")){
            harga = 15000;
        }else if(item.equals(("Robusta Coffee"))){
            harga = 17000;
        }else if(item.equals("Liberian Coffee")){
            harga = 20000;
        }else if(item.equals("Excelsa Coffee")){
            harga = 22000;
        }else{
            JOptionPane.showMessageDialog(null, "Anda belum Memilih", "EROR", JOptionPane.ERROR_MESSAGE);
        }
        
        
        Integer totalHarga = harga * Integer.parseInt(jumlah);
             
        lKopi.setText(item);
        fKetjumlah.setText(jumlah);
        lHarga.setText("Rp. "+harga.toString());
        fTotal.setText("Rp. "+totalHarga.toString());
        
    }//GEN-LAST:event_bTambahActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        // TODO add your handling code here:
        int Konfirmasi = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?", "Konfirmasi Keluar", 
        JOptionPane.YES_NO_OPTION);
        if (Konfirmasi == JOptionPane.YES_OPTION) {
        System.exit(0); 
        }
    }//GEN-LAST:event_bKeluarActionPerformed

    private void fJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fJenisActionPerformed

    private void fJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fJumlahActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Jenis = fJenis.getSelectedItem().toString();
        String Jumlah = fJumlah.getText();
        String Harga = lHarga.getText();
        String Total = fTotal.getText();
        
        JOptionPane.showMessageDialog(null, "Kopi " + Jenis + "\nJumlah "+ Jumlah + "\nHarga " + Harga + "\nTotal "+ Total);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz1pemvis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz1pemvis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz1pemvis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz1pemvis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz1pemvis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bTambah;
    private javax.swing.JComboBox<String> fJenis;
    private javax.swing.JTextField fJumlah;
    private javax.swing.JLabel fKetjumlah;
    private javax.swing.JLabel fTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lHarga;
    private javax.swing.JLabel lKopi;
    // End of variables declaration//GEN-END:variables
}
