/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasprak3;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author LENOVO SLIM 3 R3
 */
public class Perpustakaan extends javax.swing.JFrame {

    /**
     * Creates new form Perpustakaan
     */
    public Perpustakaan() {
        initComponents();
        init();
        
    }
    public void init(){
        setImage("cover1.jpeg", lCover1);
        setImage("cover2.jpeg", lCover2);
        setImage("cover3.png", lCover3);
        setImage("cover12.jpg", lCover5);
        setImage("cover13.jpg", lCover6);
        setImage("cover9.jpg", lCover7);
        setImage("cover7.jpg", lCover4);
        setImage("cover6.jpeg", lCover8);
        setImage("cover10.jpg", lCover9);
        setImage("buku.png", lBuku);
        
        lJudul.setVisible(false);
        lPenerbit.setVisible(false);
        lTahun.setVisible(false);
        lPenulis.setVisible(false);
        fPenerbit.setVisible(false);
        fJudul.setVisible(false);
        fTahun.setVisible(false);
        fPenulis.setVisible(false);
        
    }
    public void setImage(String Gambar, JLabel Label){
        ImageIcon Cover1 = new ImageIcon(getClass().getResource(Gambar));
        
                Image cover1 = Cover1.getImage().getScaledInstance(Label.getWidth(), Label.getHeight(), Image.SCALE_SMOOTH ); 
                
                 Label.setIcon(new ImageIcon(cover1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        lCover1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bPanel1 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        lCover2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bPanel2 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        lCover3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bPanel3 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        lCover5 = new javax.swing.JLabel();
        bPanel4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lCover6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bPanel5 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        lCover7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bPanel6 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        lCover4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bPanel7 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lCover8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bPanel8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        bPanel10 = new javax.swing.JButton();
        lCover9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lPanah = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        lJudul = new javax.swing.JLabel();
        lTahun = new javax.swing.JLabel();
        fJudul = new javax.swing.JTextField();
        fTahun = new javax.swing.JTextField();
        lPenulis = new javax.swing.JLabel();
        fPenulis = new javax.swing.JTextField();
        lPenerbit = new javax.swing.JLabel();
        fPenerbit = new javax.swing.JTextField();
        lBuku = new javax.swing.JLabel();

        jLabel16.setText("jLabel16");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(148, 166, 132));
        jPanel1.setLayout(new java.awt.GridLayout(3, 3, 4, 4));

        jPanel14.setBackground(new java.awt.Color(255, 105, 105));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(lCover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 93, 109));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PERAHU KERTAS");
        jPanel14.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        bPanel1.setBackground(new java.awt.Color(199, 0, 57));
        bPanel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bPanel1.setForeground(new java.awt.Color(255, 255, 255));
        bPanel1.setText("Detail");
        bPanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPanel1ActionPerformed(evt);
            }
        });
        jPanel14.add(bPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 156, -1));

        jPanel1.add(jPanel14);

        jPanel13.setBackground(new java.awt.Color(255, 105, 105));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(lCover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 93, 109));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PELATIHAN ESC");
        jPanel13.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        bPanel2.setBackground(new java.awt.Color(199, 0, 57));
        bPanel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bPanel2.setForeground(new java.awt.Color(255, 255, 255));
        bPanel2.setText("Detail");
        bPanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPanel2ActionPerformed(evt);
            }
        });
        jPanel13.add(bPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 156, -1));

        jPanel1.add(jPanel13);

        jPanel12.setBackground(new java.awt.Color(255, 105, 105));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel12.add(lCover3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 10, 93, 109));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BUKU AGENDA");
        jPanel12.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        bPanel3.setBackground(new java.awt.Color(199, 0, 57));
        bPanel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bPanel3.setForeground(new java.awt.Color(255, 255, 255));
        bPanel3.setText("Detail");
        bPanel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPanel3ActionPerformed(evt);
            }
        });
        jPanel12.add(bPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 156, -1));

        jPanel1.add(jPanel12);

        jPanel11.setBackground(new java.awt.Color(255, 105, 105));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel11.add(lCover5, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 12, 93, 109));

        bPanel4.setBackground(new java.awt.Color(199, 0, 57));
        bPanel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bPanel4.setForeground(new java.awt.Color(255, 255, 255));
        bPanel4.setText("Detail");
        bPanel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPanel4ActionPerformed(evt);
            }
        });
        jPanel11.add(bPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 156, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("HIDUP MATI ");
        jPanel11.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jPanel1.add(jPanel11);

        jPanel10.setBackground(new java.awt.Color(255, 105, 105));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel10.add(lCover6, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 12, 93, 109));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PENAKLUK SUBUH");
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        bPanel5.setBackground(new java.awt.Color(199, 0, 57));
        bPanel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bPanel5.setForeground(new java.awt.Color(255, 255, 255));
        bPanel5.setText("Detail");
        bPanel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPanel5ActionPerformed(evt);
            }
        });
        jPanel10.add(bPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 156, -1));

        jPanel1.add(jPanel10);

        jPanel9.setBackground(new java.awt.Color(255, 105, 105));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(lCover7, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 12, 93, 109));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DISEBALIK DINARA");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        bPanel6.setBackground(new java.awt.Color(199, 0, 57));
        bPanel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bPanel6.setForeground(new java.awt.Color(255, 255, 255));
        bPanel6.setText("Detail");
        bPanel6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPanel6ActionPerformed(evt);
            }
        });
        jPanel9.add(bPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 156, -1));

        jPanel1.add(jPanel9);

        jPanel8.setBackground(new java.awt.Color(255, 105, 105));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(lCover4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 12, 93, 109));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PULANG");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        bPanel7.setBackground(new java.awt.Color(199, 0, 57));
        bPanel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bPanel7.setForeground(new java.awt.Color(255, 255, 255));
        bPanel7.setText("Detail");
        bPanel7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPanel7ActionPerformed(evt);
            }
        });
        jPanel8.add(bPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 156, -1));

        jPanel1.add(jPanel8);

        jPanel5.setBackground(new java.awt.Color(255, 105, 105));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(lCover8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 93, 109));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PELAUT ULUNG");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        bPanel8.setBackground(new java.awt.Color(199, 0, 57));
        bPanel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bPanel8.setForeground(new java.awt.Color(255, 255, 255));
        bPanel8.setText("Detail");
        bPanel8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPanel8ActionPerformed(evt);
            }
        });
        jPanel5.add(bPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 156, -1));

        jPanel1.add(jPanel5);

        jPanel4.setBackground(new java.awt.Color(255, 105, 105));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("KREATIF ATAU MATI");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        bPanel10.setBackground(new java.awt.Color(199, 0, 57));
        bPanel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bPanel10.setForeground(new java.awt.Color(255, 255, 255));
        bPanel10.setText("Detail");
        bPanel10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPanel10ActionPerformed(evt);
            }
        });
        jPanel4.add(bPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 156, -1));
        jPanel4.add(lCover9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 93, 109));

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 581));

        jPanel2.setBackground(new java.awt.Color(20, 30, 70));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(20, 30, 70));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Perpustakaan");
        jPanel2.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        lPanah.setText("       ");
        jPanel2.add(lPanah, java.awt.BorderLayout.LINE_START);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel2.setText("         ");
        jPanel2.add(jLabel2, java.awt.BorderLayout.PAGE_END);

        jPanel15.setBackground(new java.awt.Color(199, 0, 57));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Hallo!");
        jPanel15.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        label3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Untuk melihat detail buku");
        jPanel15.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        label4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("Bisa mengklik tombol detail ");
        jPanel15.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        label5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("disamping");
        jPanel15.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        lJudul.setBackground(new java.awt.Color(255, 255, 255));
        lJudul.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lJudul.setForeground(new java.awt.Color(255, 255, 255));
        lJudul.setText("Judul Buku :");
        jPanel15.add(lJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 54, -1, -1));

        lTahun.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lTahun.setForeground(new java.awt.Color(255, 255, 255));
        lTahun.setText("Tahun Terbit :");
        jPanel15.add(lTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 136, -1, -1));

        fJudul.setEditable(false);
        fJudul.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel15.add(fJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 85, 310, 33));

        fTahun.setEditable(false);
        fTahun.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTahunActionPerformed(evt);
            }
        });
        jPanel15.add(fTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 167, 310, 32));

        lPenulis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lPenulis.setForeground(new java.awt.Color(255, 255, 255));
        lPenulis.setText("Penulis :");
        jPanel15.add(lPenulis, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 217, -1, -1));

        fPenulis.setEditable(false);
        fPenulis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fPenulis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fPenulisActionPerformed(evt);
            }
        });
        jPanel15.add(fPenulis, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 248, 310, 33));

        lPenerbit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lPenerbit.setForeground(new java.awt.Color(255, 255, 255));
        lPenerbit.setText("Penerbit :");
        jPanel15.add(lPenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 299, -1, -1));

        fPenerbit.setEditable(false);
        fPenerbit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fPenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fPenerbitActionPerformed(evt);
            }
        });
        jPanel15.add(fPenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 330, 310, -1));
        jPanel15.add(lBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 70, 110));

        jPanel2.add(jPanel15, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 0, 390, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPanel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPanel4ActionPerformed
        lJudul.setVisible(true);
        lPenerbit.setVisible(true);
        lTahun.setVisible(true);
        lPenulis.setVisible(true);
        fPenerbit.setVisible(true);
        fJudul.setVisible(true);
        fTahun.setVisible(true);
        fPenulis.setVisible(true);
        label1.setVisible(false);
        label3.setVisible(false);
        label4.setVisible(false);
        label5.setVisible(false);
        fPenerbit.setText("PT. Cahya Gemilang");
        fPenulis.setText("Waddatuhrahman");
        fTahun.setText("2010");
        fJudul.setText("Hidup Bukan untuk Mati");
    }//GEN-LAST:event_bPanel4ActionPerformed

    private void bPanel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPanel3ActionPerformed
        lJudul.setVisible(true);
        lPenerbit.setVisible(true);
        lTahun.setVisible(true);
        lPenulis.setVisible(true);
        fPenerbit.setVisible(true);
        fJudul.setVisible(true);
        fTahun.setVisible(true);
        fPenulis.setVisible(true);
        label1.setVisible(false);
        label3.setVisible(false);
        label4.setVisible(false);
        label5.setVisible(false);
        fPenerbit.setText("PT. Sido Makmur");
        fPenulis.setText("Luis Simanjuntak");
        fTahun.setText("2012");
        fJudul.setText("Buku Agenda");
    }//GEN-LAST:event_bPanel3ActionPerformed

    private void bPanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPanel2ActionPerformed
        lJudul.setVisible(true);
        lPenerbit.setVisible(true);
        lTahun.setVisible(true);
        lPenulis.setVisible(true);
        fPenerbit.setVisible(true);
        fJudul.setVisible(true);
        fTahun.setVisible(true);
        fPenulis.setVisible(true);
        label1.setVisible(false);
        label3.setVisible(false);
        label4.setVisible(false);
        label5.setVisible(false);
        fPenerbit.setText("PT. Sumber Rejeki");
        fPenulis.setText("Edi Cahyanto");
        fTahun.setText("2013");
        fJudul.setText("Pelatihan ESC");
    }//GEN-LAST:event_bPanel2ActionPerformed

    private void bPanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPanel1ActionPerformed
        lJudul.setVisible(true);
        lPenerbit.setVisible(true);
        lTahun.setVisible(true);
        lPenulis.setVisible(true);
        fPenerbit.setVisible(true);
        fJudul.setVisible(true);
        fTahun.setVisible(true);
        fPenulis.setVisible(true);
        label1.setVisible(false);
        label3.setVisible(false);
        label4.setVisible(false);
        label5.setVisible(false);
        fPenerbit.setText("PT. Setia Budi");
        fPenulis.setText("Rudi Widodo");
        fTahun.setText("2017");
        fJudul.setText("Perahu Kertas");
    }//GEN-LAST:event_bPanel1ActionPerformed

    private void bPanel6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPanel6ActionPerformed
        lJudul.setVisible(true);
        lPenerbit.setVisible(true);
        lTahun.setVisible(true);
        lPenulis.setVisible(true);
        fPenerbit.setVisible(true);
        fJudul.setVisible(true);
        fTahun.setVisible(true);
        fPenulis.setVisible(true);
        label1.setVisible(false);
        label3.setVisible(false);
        label4.setVisible(false);
        label5.setVisible(false);
        fPenerbit.setText("PT. Abadi Jaya");
        fPenulis.setText("Dayang Noor");
        fTahun.setText("2004");
        fJudul.setText("Disebalik Dinara");
    }//GEN-LAST:event_bPanel6ActionPerformed

    private void bPanel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPanel5ActionPerformed
        lJudul.setVisible(true);
        lPenerbit.setVisible(true);
        lTahun.setVisible(true);
        lPenulis.setVisible(true);
        fPenerbit.setVisible(true);
        fJudul.setVisible(true);
        fTahun.setVisible(true);
        fPenulis.setVisible(true);
        label1.setVisible(false);
        label3.setVisible(false);
        label4.setVisible(false);
        label5.setVisible(false);
        fPenerbit.setText("PT. Sido Makmur");
        fPenulis.setText("Muhammad Iqbal");
        fTahun.setText("2008");
        fJudul.setText("Penakluk Subuh");
    }//GEN-LAST:event_bPanel5ActionPerformed

    private void bPanel7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPanel7ActionPerformed
        lJudul.setVisible(true);
        lPenerbit.setVisible(true);
        lTahun.setVisible(true);
        lPenulis.setVisible(true);
        fPenerbit.setVisible(true);
        fJudul.setVisible(true);
        fTahun.setVisible(true);
        fPenulis.setVisible(true);
        label1.setVisible(false);
        label3.setVisible(false);
        label4.setVisible(false);
        label5.setVisible(false);
        fPenerbit.setText("PT. Maju Mapan");
        fPenulis.setText("Tere Liye");
        fTahun.setText("2015");
        fJudul.setText("Pulang");
    }//GEN-LAST:event_bPanel7ActionPerformed

    private void bPanel10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPanel10ActionPerformed
        lJudul.setVisible(true);
        lPenerbit.setVisible(true);
        lTahun.setVisible(true);
        lPenulis.setVisible(true);
        fPenerbit.setVisible(true);
        fJudul.setVisible(true);
        fTahun.setVisible(true);
        fPenulis.setVisible(true);
        label1.setVisible(false);
        label3.setVisible(false);
        label4.setVisible(false);
        label5.setVisible(false);
        fPenerbit.setText("PT. Sido Makmur");
        fPenulis.setText("Yusuh al Hajaj");
        fTahun.setText("2020");
        fJudul.setText("Kreatif atau Mati");
    }//GEN-LAST:event_bPanel10ActionPerformed

    private void bPanel8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPanel8ActionPerformed
        lJudul.setVisible(true);
        lPenerbit.setVisible(true);
        lTahun.setVisible(true);
        lPenulis.setVisible(true);
        fPenerbit.setVisible(true);
        fJudul.setVisible(true);
        fTahun.setVisible(true);
        fPenulis.setVisible(true);
        label1.setVisible(false);
        label3.setVisible(false);
        label4.setVisible(false);
        label5.setVisible(false);
        fPenerbit.setText("PT. Lampu Kehidupan");
        fPenulis.setText("Doni Van Scheneuman");
        fTahun.setText("2019");
        fJudul.setText("Pelaut Ulung");
    }//GEN-LAST:event_bPanel8ActionPerformed

    private void fTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fTahunActionPerformed

    private void fPenulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fPenulisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fPenulisActionPerformed

    private void fPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fPenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fPenerbitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perpustakaan().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bPanel1;
    private javax.swing.JButton bPanel10;
    private javax.swing.JButton bPanel2;
    private javax.swing.JButton bPanel3;
    private javax.swing.JButton bPanel4;
    private javax.swing.JButton bPanel5;
    private javax.swing.JButton bPanel6;
    private javax.swing.JButton bPanel7;
    private javax.swing.JButton bPanel8;
    private javax.swing.JTextField fJudul;
    private javax.swing.JTextField fPenerbit;
    private javax.swing.JTextField fPenulis;
    private javax.swing.JTextField fTahun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lBuku;
    private javax.swing.JLabel lCover1;
    private javax.swing.JLabel lCover2;
    private javax.swing.JLabel lCover3;
    private javax.swing.JLabel lCover4;
    private javax.swing.JLabel lCover5;
    private javax.swing.JLabel lCover6;
    private javax.swing.JLabel lCover7;
    private javax.swing.JLabel lCover8;
    private javax.swing.JLabel lCover9;
    private javax.swing.JLabel lJudul;
    private javax.swing.JLabel lPanah;
    private javax.swing.JLabel lPenerbit;
    private javax.swing.JLabel lPenulis;
    private javax.swing.JLabel lTahun;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    // End of variables declaration//GEN-END:variables
}
