/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugaspraktikum1;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO SLIM 3 R3
 */
public class Formpendaftaran extends javax.swing.JFrame {

    /**
     * Creates new form Formpendaftaran
     */
    public Formpendaftaran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        bgKelamin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fNama = new javax.swing.JTextField();
        fNim = new javax.swing.JTextField();
        fProdi = new javax.swing.JTextField();
        fFakultas = new javax.swing.JComboBox<>();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        fAlamat = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bSimpan = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("JENIS KELAMIN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("UNIVERSITAS TRUNOJOYO MADURA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        fNama.setBackground(new java.awt.Color(0,0,0,0)
        );
        fNama.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fNama.setForeground(new java.awt.Color(204, 204, 204));
        fNama.setText("Masukkan Nama");
        fNama.setToolTipText("Nama anda");
        fNama.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        fNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fNamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fNamaFocusLost(evt);
            }
        });
        fNama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fNamaMouseClicked(evt);
            }
        });
        fNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNamaActionPerformed(evt);
            }
        });
        jPanel1.add(fNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 300, 30));

        fNim.setBackground(new java.awt.Color(0,0,0,0)
        );
        fNim.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fNim.setForeground(new java.awt.Color(204, 204, 204));
        fNim.setText("Masukkan NIM");
        fNim.setToolTipText("NIM anda");
        fNim.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        fNim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fNimFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fNimFocusLost(evt);
            }
        });
        fNim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fNimMouseClicked(evt);
            }
        });
        jPanel1.add(fNim, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 300, 30));

        fProdi.setBackground(new java.awt.Color(0,0,0,0)
        );
        fProdi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fProdi.setForeground(new java.awt.Color(204, 204, 204));
        fProdi.setText("Masukkan Prodi");
        fProdi.setToolTipText("Prodi anda");
        fProdi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        fProdi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fProdiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fProdiFocusLost(evt);
            }
        });
        jPanel1.add(fProdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 300, 30));

        fFakultas.setBackground(new java.awt.Color(0,0,0,0));
        fFakultas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fFakultas.setForeground(new java.awt.Color(255, 255, 255));
        fFakultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Fakultas anda", "FAKULTAS TEKNIK", "FAKULTAS PENDIDIKAN", "FAKULTAS KEISLAMAN", "FAKULTAS ILMU SOSIAL DAN BUDAYA", "FAKULATAS EKONOMI DAN BISNIS", "FAKULTAS PERTANIAN", "FAKULTAS HUKUM" }));
        fFakultas.setToolTipText("Fakultas anda");
        fFakultas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(fFakultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 300, -1));

        bgKelamin.add(rbLaki);
        rbLaki.setForeground(new java.awt.Color(255, 255, 255));
        rbLaki.setText("LAKI-LAKI");
        jPanel1.add(rbLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        bgKelamin.add(rbPerempuan);
        rbPerempuan.setForeground(new java.awt.Color(255, 255, 255));
        rbPerempuan.setText("PEREMPUAN");
        jPanel1.add(rbPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PRODI");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        fAlamat.setBackground(new java.awt.Color(0,0,0,0));
        fAlamat.setColumns(20);
        fAlamat.setForeground(new java.awt.Color(255, 255, 255));
        fAlamat.setRows(5);
        fAlamat.setToolTipText("Alamat anda");
        fAlamat.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true), "Alamat", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(fAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 300, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugaspraktikum1/images-removebg-preview-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NAMA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NIM");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("FAKULTAS");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        bSimpan.setBackground(new java.awt.Color(153, 0, 0));
        bSimpan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bSimpan.setForeground(new java.awt.Color(255, 255, 255));
        bSimpan.setText("SIMPAN");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(bSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 150, 50));

        bHapus.setBackground(new java.awt.Color(153, 0, 0));
        bHapus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bHapus.setForeground(new java.awt.Color(255, 255, 255));
        bHapus.setText("HAPUS");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        jPanel1.add(bHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 150, 50));

        bKeluar.setBackground(new java.awt.Color(153, 0, 0));
        bKeluar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bKeluar.setForeground(new java.awt.Color(255, 255, 255));
        bKeluar.setText("KELUAR");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(bKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 300, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FORMULIR PENDAFTARAN UKM");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 280, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugaspraktikum1/ungu1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 402, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        String nama = fNama.getText();
        String nim = fNim.getText();
        String prodi = fProdi.getText();
        String alamat = fAlamat.getText();
        String fakultas = fFakultas.getSelectedItem().toString();
        rbLaki.setActionCommand("Laki-laki");
        rbPerempuan.setActionCommand("Perempuan");

        if (nama.equals("Masukkan Nama") || nim.equals("Masukkan NIM") || prodi.equals("Masukkan Prodi") || fakultas.equals("Pilih Fakultas anda")) {
            JOptionPane.showMessageDialog(null, "Harap isi semua field!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (nama.isEmpty() || nim.isEmpty() || prodi.isEmpty() || alamat.isEmpty() || fakultas.isEmpty() || (bgKelamin.getSelection() == null)) {
            JOptionPane.showMessageDialog(null, "Harap isi semua field!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String kelamin = bgKelamin.getSelection().getActionCommand();
            JOptionPane.showMessageDialog(null, "Nama " + nama + "\nNIM " + nim + "\nProdi " + prodi + "\nAlamat " + alamat + "\nFakultas " + fakultas + "\nKelamin " + kelamin);
        }
        
        
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        fNama.setText("");
        fNim.setText("");
        fProdi.setText("");
        fAlamat.setText("");
        fFakultas.setSelectedItem("Pilih Fakultas anda");
        bgKelamin.clearSelection();
        
    }//GEN-LAST:event_bHapusActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
       
        int Konfirmasi = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);

        if (Konfirmasi == JOptionPane.YES_OPTION) {
            System.exit(0); 
        }
    }//GEN-LAST:event_bKeluarActionPerformed

    private void fNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNamaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fNamaActionPerformed

    private void fNamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fNamaMouseClicked
        // TODO add your handling code here:
//        if (fNama.getText().equals("Masukkan Nama")) {
//        fNama.setText("");
//        fNama.setForeground(new Color(253,253,253));
//        }
    }//GEN-LAST:event_fNamaMouseClicked

    private void fNamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fNamaFocusGained
        // TODO add your handling code here:
        if (fNama.getText().equals("Masukkan Nama")) {
        fNama.setText("");
        fNama.setForeground(new Color(253,253,253));
        }
    }//GEN-LAST:event_fNamaFocusGained

    private void fNamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fNamaFocusLost
        // TODO add your handling code here:
        if (fNama.getText().equals("")) {
        fNama.setText("Masukkan Nama");
        fNama.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_fNamaFocusLost

    private void fNimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fNimFocusGained
        // TODO add your handling code here:
        if (fNim.getText().equals("Masukkan NIM")) {
        fNim.setText("");
        fNim.setForeground(new Color(253,253,253));
        }
    }//GEN-LAST:event_fNimFocusGained

    private void fNimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fNimFocusLost
        // TODO add your handling code here:
        if (fNim.getText().equals("")) {
        fNim.setText("Masukkan NIM");
        fNim.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_fNimFocusLost

    private void fNimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fNimMouseClicked
        // TODO add your handling code here:
//        if (fNim.getText().equals("Masukkan Nama")) {
//        fNim.setText("");
//        fNim.setForeground(new Color(253,253,253));
//        }
    }//GEN-LAST:event_fNimMouseClicked

    private void fProdiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fProdiFocusGained
        if (fProdi.getText().equals("Masukkan Prodi")) {
        fProdi.setText("");
        fProdi.setForeground(new Color(253,253,253));
        }
    }//GEN-LAST:event_fProdiFocusGained

    private void fProdiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fProdiFocusLost
        if (fProdi.getText().equals("")) {
        fProdi.setText("Masukkan Prodi");
        fProdi.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_fProdiFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formpendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formpendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formpendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formpendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formpendaftaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bSimpan;
    private javax.swing.ButtonGroup bgKelamin;
    private javax.swing.JTextArea fAlamat;
    private javax.swing.JComboBox<String> fFakultas;
    private javax.swing.JTextField fNama;
    private javax.swing.JTextField fNim;
    private javax.swing.JTextField fProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    // End of variables declaration//GEN-END:variables
}
