


import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author LENOVO SLIM 3 R3
 */
public class Frame1 extends javax.swing.JInternalFrame {
         DefaultListModel<String> tugas = new DefaultListModel<>();
         ArrayList<String> detailtugas = new ArrayList<>();
//         
         

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
        jListTugas.setModel(tugas);
        jListTugas.addListSelectionListener(new ListSelectionListener() {
        public void valueChanged(ListSelectionEvent evt) {
        if (!evt.getValueIsAdjusting()) {
            AmbilItem();
        }
    }
    });
    } 
    
    private void AmbilItem() {
    int pilihan = jListTugas.getSelectedIndex();
    if (pilihan != -1) {
        String pilihdetail = detailtugas.get(pilihan);

        fDetail2.setText(pilihdetail);
    }
}



      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fDl = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fMataKuliah = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fDetail = new javax.swing.JTextArea();
        bSimpan = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        bSimpan1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTugas = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        fDetail2 = new javax.swing.JTextArea();
        bHapus = new javax.swing.JButton();
        lBuku = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(106, 156, 137));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jTabbedPane1.setBackground(new java.awt.Color(215, 192, 174));

        jPanel2.setBackground(new java.awt.Color(150, 126, 118));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 238, 238));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TAMBAH TUGAS");
        jPanel2.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(215, 192, 174));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 60, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DETAIL TUGAS");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 176, -1, -1));

        fDl.setBackground(new java.awt.Color(0,0,0,0));
        fDl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fDl.setForeground(new java.awt.Color(255, 255, 255));
        fDl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        fDl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fDlFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fDlFocusLost(evt);
            }
        });
        fDl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fDlActionPerformed(evt);
            }
        });
        jPanel4.add(fDl, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 106, 244, 40));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MATA KULIAH");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 55, -1, -1));

        fMataKuliah.setBackground(new java.awt.Color(0,0,0,0));
        fMataKuliah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fMataKuliah.setForeground(new java.awt.Color(255, 255, 255));
        fMataKuliah.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        fMataKuliah.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fMataKuliahFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fMataKuliahFocusLost(evt);
            }
        });
        fMataKuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fMataKuliahActionPerformed(evt);
            }
        });
        jPanel4.add(fMataKuliah, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 47, 244, 41));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DEADLINE TUGAS");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 106, -1, -1));

        fDetail.setColumns(20);
        fDetail.setRows(5);
        fDetail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fDetailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fDetailFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(fDetail);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 207, 462, -1));

        bSimpan.setBackground(new java.awt.Color(0, 255, 0));
        bSimpan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bSimpan.setForeground(new java.awt.Color(255, 255, 255));
        bSimpan.setText("SIMPAN");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });
        jPanel4.add(bSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 348, 229, -1));

        jPanel6.setBackground(new java.awt.Color(150, 126, 118));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bSimpan1.setBackground(new java.awt.Color(255, 0, 0));
        bSimpan1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bSimpan1.setForeground(new java.awt.Color(255, 255, 255));
        bSimpan1.setText("BERSIHKAN");
        bSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(bSimpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(315, Short.MAX_VALUE)
                .addComponent(bSimpan1)
                .addContainerGap())
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 500, 360));

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Tambah Tugas", jPanel2);

        jPanel3.setBackground(new java.awt.Color(150, 126, 118));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DAFTAR TUGAS");
        jPanel3.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(215, 192, 174));

        jListTugas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListTugas);

        fDetail2.setEditable(false);
        fDetail2.setColumns(20);
        fDetail2.setRows(5);
        jScrollPane3.setViewportView(fDetail2);

        bHapus.setBackground(new java.awt.Color(255, 0, 0));
        bHapus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bHapus.setForeground(new java.awt.Color(255, 255, 255));
        bHapus.setText("HAPUS");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        lBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buku.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TUGAS");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DETAIL");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bHapus)))
                        .addGap(40, 40, 40)
                        .addComponent(lBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(bHapus)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(1, 1, 1)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Daftar Tugas", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fDlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fDlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fDlActionPerformed

    private void fMataKuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fMataKuliahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fMataKuliahActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        String matkul = fMataKuliah.getText();
        String deadline = fDl.getText();
        String detail = fDetail.getText();
        
        if (matkul.equals("")){
            JOptionPane.showMessageDialog(null, "Matakuliah belum diisi!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (deadline.equals("")){
            JOptionPane.showMessageDialog(null, "Tanggal deadline belum diisi!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if(detail.equals("")) {
            JOptionPane.showMessageDialog(null, "Detail belum diisi!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {

            tugas.addElement("> " + matkul + "( dl: " + deadline + ")");

            detailtugas.add(detail);
            fMataKuliah.setText("");


            fDl.setText("");
            fDetail.setText("");
            }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
    int pilihIndex = jListTugas.getSelectedIndex();
    if (pilihIndex != -1) {
    int konfirmasi = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus item ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (konfirmasi == JOptionPane.YES_OPTION) {
        tugas.remove(pilihIndex);
        detailtugas.remove(pilihIndex);
//        for (int i = pilihIndex; i < tugas.getSize(); i++) {
//            String itemlist = tugas.getElementAt(i);
//            itemlist = itemlist.replaceAll("\\d+", String.valueOf(i + 1));
//            tugas.setElementAt(itemlist, i);
//        }
        fDetail2.setText("");
    }}
    }//GEN-LAST:event_bHapusActionPerformed

    private void bSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpan1ActionPerformed
        // TODO add your handling code here:
        fMataKuliah.setText("");
        fDl.setText("");
        fDetail.setText("");
    }//GEN-LAST:event_bSimpan1ActionPerformed

    private void fMataKuliahFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fMataKuliahFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fMataKuliahFocusGained

    private void fMataKuliahFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fMataKuliahFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fMataKuliahFocusLost

    private void fDlFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fDlFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fDlFocusGained

    private void fDlFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fDlFocusLost
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_fDlFocusLost

    private void fDetailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fDetailFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fDetailFocusGained

    private void fDetailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fDetailFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fDetailFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bSimpan1;
    private javax.swing.JTextArea fDetail;
    private javax.swing.JTextArea fDetail2;
    private javax.swing.JTextField fDl;
    private javax.swing.JTextField fMataKuliah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jListTugas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lBuku;
    // End of variables declaration//GEN-END:variables
}
