/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasprak2;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO SLIM 3 R3
 */
public class Gaji extends javax.swing.JFrame  {
    double GajiBruto;
    double GajiBersih;

    /**
     * Creates new form Gaji
     */
    public Gaji() {
        initComponents();
        init(); 
        
    }

    public void init(){
        setImage();
    }
    public void setImage(){
         ImageIcon Logoperusahaan = new ImageIcon(getClass().getResource("Logo M.png")); 
         
         Image IconLogo = Logoperusahaan.getImage().getScaledInstance(Logo.getWidth(), Logo.getHeight(),Image.SCALE_SMOOTH );     
         
         Logo.setIcon(new ImageIcon(IconLogo));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fJamKerja = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fTarif = new javax.swing.JTextField();
        bGjBruto = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        fBruto = new javax.swing.JTextField();
        bGjBersih = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        fBersih = new javax.swing.JTextField();
        bSimpan = new javax.swing.JButton();
        bReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(18, 72, 107));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PT. MAJU JAYA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Indonesia");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        Logo.setText("jLabel8");
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 170, 210));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 440));

        jPanel2.setBackground(new java.awt.Color(236, 229, 199));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("APLIKASI SLIP GAJI KARYAWAN");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Jumlah jam kerja 1 Minggu");

        fJamKerja.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        fJamKerja.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fJamKerjaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fJamKerjaFocusLost(evt);
            }
        });
        fJamKerja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fJamKerjaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Tarif Per-jam");

        fTarif.setEditable(false);
        fTarif.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        fTarif.setText("Rp. 10000");
        fTarif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTarifActionPerformed(evt);
            }
        });

        bGjBruto.setBackground(new java.awt.Color(24, 111, 101));
        bGjBruto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bGjBruto.setForeground(new java.awt.Color(255, 255, 255));
        bGjBruto.setText("Hitung Gaji Bruto");
        bGjBruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGjBrutoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Gaji Bruto");

        fBruto.setEditable(false);
        fBruto.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        fBruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fBrutoActionPerformed(evt);
            }
        });

        bGjBersih.setBackground(new java.awt.Color(24, 111, 101));
        bGjBersih.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bGjBersih.setForeground(new java.awt.Color(255, 255, 255));
        bGjBersih.setText("Hitung Gaji Bersih");
        bGjBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGjBersihActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Gaji Bersih");

        fBersih.setEditable(false);
        fBersih.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        fBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fBersihActionPerformed(evt);
            }
        });

        bSimpan.setBackground(new java.awt.Color(24, 111, 101));
        bSimpan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bSimpan.setForeground(new java.awt.Color(255, 255, 255));
        bSimpan.setText("SIMPAN");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bReset.setBackground(new java.awt.Color(24, 111, 101));
        bReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bReset.setForeground(new java.awt.Color(255, 255, 255));
        bReset.setText("RESET");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fBersih, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(95, 95, 95)
                            .addComponent(jLabel3))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jLabel4))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fJamKerja, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(fTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bGjBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(jLabel6))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(bGjBersih, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jLabel7))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(bSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fJamKerja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5)))
                .addComponent(fTarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bGjBruto)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel6))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(fBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(bGjBersih)
                .addGap(5, 5, 5)
                .addComponent(jLabel7)
                .addGap(0, 0, 0)
                .addComponent(fBersih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSimpan)
                    .addComponent(bReset)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 500, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGjBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGjBersihActionPerformed
         
            GajiBersih = GajiBruto * 0.9;
            fBersih.setText("Rp. " + Double.toString(GajiBersih));
        
    }//GEN-LAST:event_bGjBersihActionPerformed

    private void fJamKerjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fJamKerjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fJamKerjaActionPerformed

    private void fTarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTarifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fTarifActionPerformed

    private void bGjBrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGjBrutoActionPerformed
       int Lembur;
       String JamKerja = fJamKerja.getText();
       int Tarif = 10000 ;
       
       int intJam = Integer.parseInt(JamKerja);
     
       if (intJam > 40 ){
           Lembur = intJam - 40;
           GajiBruto = (40 * 10000)+ (Lembur * (10000*1.5));
       }else {
           GajiBruto = intJam * 10000;
       }
       fTarif.setText("Rp. 10000");
       fBruto.setText("Rp. "+ Double.toString(GajiBruto));
        
    }//GEN-LAST:event_bGjBrutoActionPerformed

    private void fBrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fBrutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fBrutoActionPerformed

    private void fBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fBersihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fBersihActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        JOptionPane.showMessageDialog(this, "Total Gaji Bersih anda sebesar Rp."+ GajiBersih);
        fBersih.setText("");
        fBruto.setText("");
        fJamKerja.setText("");
        
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
        fBersih.setText("");
        fBruto.setText("");
        fJamKerja.setText("");
    }//GEN-LAST:event_bResetActionPerformed

    private void fJamKerjaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fJamKerjaFocusGained
        // TODO add your handling code here:
        if (fJamKerja.getText().equals("Masukkan Jam Kerja")) {
        fJamKerja.setText("");
        fJamKerja.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_fJamKerjaFocusGained

    private void fJamKerjaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fJamKerjaFocusLost
        // TODO add your handling code here:
        if (fJamKerja.getText().equals("")) {
        fJamKerja.setText("Masukkan Jam Kerja");
        fJamKerja.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_fJamKerjaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gaji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton bGjBersih;
    private javax.swing.JButton bGjBruto;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bSimpan;
    private javax.swing.JTextField fBersih;
    private javax.swing.JTextField fBruto;
    private javax.swing.JTextField fJamKerja;
    private javax.swing.JTextField fTarif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
