/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasprak2;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO SLIM 3 R3
 */
public class Warung extends javax.swing.JFrame {
    private int angka = 0;
    private String makanan;
    private int Harga;

    /**
     * Creates new form Warung
     */
    public Warung() {
        initComponents();
        init();
        
    }
    public void init(){
        setImage("nasgor.png", iNasgor);
        setImage("bakso.png", lBakso);
        setImage("mie ayam.png", lMie);
        setImage("gado-gado.png", lGado);
        setImage("nasi kuning.png", lNaskun);
        setImage("nasi padang.png", lNaspad);
    }
    public void setImage(String Gambar, JLabel Label){
        ImageIcon Nasgor = new ImageIcon(getClass().getResource(Gambar));
        
                Image IconNasgor = Nasgor.getImage().getScaledInstance(iNasgor.getWidth(), iNasgor.getHeight(), Image.SCALE_SMOOTH ); 
                
                Label.setIcon(new ImageIcon(IconNasgor));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgMakanan = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lJmlhBeli = new javax.swing.JLabel();
        bTambah = new javax.swing.JButton();
        bKurang = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lPesanan = new javax.swing.JLabel();
        lJumlahPesanan = new javax.swing.JLabel();
        lHarga = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bBeli = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pNaskun = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lNaskun = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        rbNasiKuning = new javax.swing.JRadioButton();
        pNaspad = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lNaspad = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rbNasiPadang = new javax.swing.JRadioButton();
        pGado = new javax.swing.JPanel();
        rbGadogado = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        lGado = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pMie = new javax.swing.JPanel();
        rbMieAyam = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        lMie = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        pBakso = new javax.swing.JPanel();
        rbBakso = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        lBakso = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pNasgor = new javax.swing.JPanel();
        rbNasiGoreng = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        iNasgor = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(24, 111, 101));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WARUNG REY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jl. Telang, Kec. Kamal, Bangkalan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasprak2/logo-removebg-preview-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(181, 203, 153));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("JUMLAH BELI");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lJmlhBeli.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lJmlhBeli.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(lJmlhBeli)
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lJmlhBeli)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        bTambah.setText("+");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bKurang.setText("-");
        bKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKurangActionPerformed(evt);
            }
        });

        jLabel6.setText("Pesanan Anda :");

        jLabel8.setText("Harga : ");

        jLabel4.setText("Total :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lPesanan))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lHarga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lJumlahPesanan))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lTotal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lPesanan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lJumlahPesanan)
                    .addComponent(lHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lTotal)))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("INFORMASI PESANANAN");

        bBeli.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bBeli.setText("BELI");
        bBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBeliActionPerformed(evt);
            }
        });

        bHapus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bHapus.setText("HAPUS");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bKurang))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTambah)
                    .addComponent(bKurang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(252, 224, 155));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(24, 111, 101));
        jLabel7.setText("MENU MAKANAN");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 32, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasprak2/makanan-removebg-preview.png"))); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, 120));

        pNaskun.setBackground(new java.awt.Color(255, 207, 150));
        pNaskun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pNaskunMouseClicked(evt);
            }
        });
        pNaskun.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel15.setText("Nasi Kuning");
        pNaskun.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lNaskun.setText("p");
        pNaskun.add(lNaskun, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 60));

        jLabel16.setText("Rp. 12.000");
        pNaskun.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        bgMakanan.add(rbNasiKuning);
        rbNasiKuning.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        rbNasiKuning.setForeground(new java.awt.Color(24, 111, 101));
        rbNasiKuning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNasiKuningActionPerformed(evt);
            }
        });
        pNaskun.add(rbNasiKuning, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jPanel3.add(pNaskun, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 150, 150));

        pNaspad.setBackground(new java.awt.Color(255, 207, 150));
        pNaspad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pNaspadMouseClicked(evt);
            }
        });
        pNaspad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel13.setText("Nasi Padang");
        pNaspad.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lNaspad.setText("p");
        pNaspad.add(lNaspad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 60));

        jLabel14.setText("Rp. 15.000");
        pNaspad.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        bgMakanan.add(rbNasiPadang);
        rbNasiPadang.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        rbNasiPadang.setForeground(new java.awt.Color(24, 111, 101));
        rbNasiPadang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNasiPadangActionPerformed(evt);
            }
        });
        pNaspad.add(rbNasiPadang, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jPanel3.add(pNaspad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 150, 150));

        pGado.setBackground(new java.awt.Color(255, 207, 150));
        pGado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pGadoMouseClicked(evt);
            }
        });
        pGado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgMakanan.add(rbGadogado);
        rbGadogado.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        rbGadogado.setForeground(new java.awt.Color(24, 111, 101));
        rbGadogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGadogadoActionPerformed(evt);
            }
        });
        pGado.add(rbGadogado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel19.setText("Gado-gado");
        pGado.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lGado.setText("p");
        pGado.add(lGado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 60));

        jLabel20.setText("Rp. 9.000");
        pGado.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jPanel3.add(pGado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 150, 150));

        pMie.setBackground(new java.awt.Color(255, 207, 150));
        pMie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pMieMouseClicked(evt);
            }
        });
        pMie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgMakanan.add(rbMieAyam);
        rbMieAyam.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        rbMieAyam.setForeground(new java.awt.Color(24, 111, 101));
        rbMieAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMieAyamActionPerformed(evt);
            }
        });
        pMie.add(rbMieAyam, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel21.setText("Mie Ayam");
        pMie.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        lMie.setText("p");
        pMie.add(lMie, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 60));

        jLabel22.setText("Rp. 13.000");
        pMie.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jPanel3.add(pMie, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 150, 150));

        pBakso.setBackground(new java.awt.Color(255, 207, 150));
        pBakso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pBaksoMouseClicked(evt);
            }
        });
        pBakso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgMakanan.add(rbBakso);
        rbBakso.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        rbBakso.setForeground(new java.awt.Color(24, 111, 101));
        rbBakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBaksoActionPerformed(evt);
            }
        });
        pBakso.add(rbBakso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel17.setText("Bakso");
        pBakso.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        lBakso.setText("p");
        pBakso.add(lBakso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 60));

        jLabel18.setText("Rp. 10.000");
        pBakso.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jPanel3.add(pBakso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 150, 150));

        pNasgor.setBackground(new java.awt.Color(255, 207, 150));
        pNasgor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pNasgorMouseClicked(evt);
            }
        });
        pNasgor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgMakanan.add(rbNasiGoreng);
        rbNasiGoreng.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        rbNasiGoreng.setForeground(new java.awt.Color(24, 111, 101));
        rbNasiGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNasiGorengActionPerformed(evt);
            }
        });
        pNasgor.add(rbNasiGoreng, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setText("Nasi Goreng");
        pNasgor.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        iNasgor.setText("p");
        pNasgor.add(iNasgor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 60));

        jLabel11.setText("Rp. 13.000");
        pNasgor.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jPanel3.add(pNasgor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 150, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKurangActionPerformed
        angka --;
            if (angka >= 0){
            lJmlhBeli.setText(Integer.toString(angka));
            } else {
                angka = 0;
                lJmlhBeli.setText(Integer.toString(angka));
            }
    }//GEN-LAST:event_bKurangActionPerformed

    private void rbNasiGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNasiGorengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNasiGorengActionPerformed

    private void rbNasiPadangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNasiPadangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNasiPadangActionPerformed

    private void bBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBeliActionPerformed
        if (angka == 0){
                JOptionPane.showMessageDialog(null, "Anda belum memilih jumlah beli!", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                rbBakso.setActionCommand("Bakso");
                rbGadogado.setActionCommand("Gado-gado");
                rbMieAyam.setActionCommand("Mie Ayam");
                rbNasiGoreng.setActionCommand("Nasi Goreng");
                rbNasiKuning.setActionCommand("Nasi Kuning");
                rbNasiPadang.setActionCommand("Nasi Padang");


                if (bgMakanan.getSelection() != null){
                    makanan = bgMakanan.getSelection().getActionCommand();
                    lPesanan.setText(makanan+"("+angka+")");    
                }else {
                    JOptionPane.showMessageDialog(null, "Anda belum memilih makanan!", "Error", JOptionPane.ERROR_MESSAGE);
                }
                
                if (makanan == "Bakso"){
                    Harga = 10000;
                } else if (makanan.equals("Gado-gado")){
                    Harga = 9000;
                } else if (makanan.equals("Mie Ayam")){
                    Harga = 13000;
                } else if (makanan.equals("Nasi Goreng")){
                    Harga = 12000;
                } else if (makanan.equals("Nasi Kuning")){
                    Harga = 12000;
                }else if(makanan.equals("Nasi Padang")){
                    Harga = 15000;
                }
                    
                
                
                
                
                lTotal.setText(Integer.toString(Harga*angka));
                lHarga.setText(Integer.toString(Harga));
                
            }
        
    }//GEN-LAST:event_bBeliActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        angka ++;
            lJmlhBeli.setText(Integer.toString(angka));
    }//GEN-LAST:event_bTambahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        lJmlhBeli.setText("0");
        lJumlahPesanan.setText("");
        lHarga.setText("");
        lPesanan.setText("");
        lTotal.setText("");
        bgMakanan.clearSelection();
        angka = 0;
    }//GEN-LAST:event_bHapusActionPerformed

    private void pNasgorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pNasgorMouseClicked
        // TODO add your handling code here:
        rbNasiGoreng.setSelected(true);
    }//GEN-LAST:event_pNasgorMouseClicked

    private void pNaspadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pNaspadMouseClicked
        // TODO add your handling code here:
        rbNasiPadang.setSelected(true);
    }//GEN-LAST:event_pNaspadMouseClicked

    private void rbNasiKuningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNasiKuningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNasiKuningActionPerformed

    private void pNaskunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pNaskunMouseClicked
        // TODO add your handling code here:
        rbNasiKuning.setSelected(true);
    }//GEN-LAST:event_pNaskunMouseClicked

    private void rbBaksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBaksoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBaksoActionPerformed

    private void pBaksoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pBaksoMouseClicked
        // TODO add your handling code here:
        rbBakso.setSelected(true);
    }//GEN-LAST:event_pBaksoMouseClicked

    private void rbGadogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGadogadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbGadogadoActionPerformed

    private void pGadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pGadoMouseClicked
        // TODO add your handling code here:
        rbGadogado.setSelected(true);
    }//GEN-LAST:event_pGadoMouseClicked

    private void rbMieAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMieAyamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMieAyamActionPerformed

    private void pMieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMieMouseClicked
        // TODO add your handling code here:
        rbMieAyam.setSelected(true);
    }//GEN-LAST:event_pMieMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Warung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBeli;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKurang;
    private javax.swing.JButton bTambah;
    private javax.swing.ButtonGroup bgMakanan;
    private javax.swing.JLabel iNasgor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lBakso;
    private javax.swing.JLabel lGado;
    private javax.swing.JLabel lHarga;
    private javax.swing.JLabel lJmlhBeli;
    private javax.swing.JLabel lJumlahPesanan;
    private javax.swing.JLabel lMie;
    private javax.swing.JLabel lNaskun;
    private javax.swing.JLabel lNaspad;
    private javax.swing.JLabel lPesanan;
    private javax.swing.JLabel lTotal;
    private javax.swing.JPanel pBakso;
    private javax.swing.JPanel pGado;
    private javax.swing.JPanel pMie;
    private javax.swing.JPanel pNasgor;
    private javax.swing.JPanel pNaskun;
    private javax.swing.JPanel pNaspad;
    private javax.swing.JRadioButton rbBakso;
    private javax.swing.JRadioButton rbGadogado;
    private javax.swing.JRadioButton rbMieAyam;
    private javax.swing.JRadioButton rbNasiGoreng;
    private javax.swing.JRadioButton rbNasiKuning;
    private javax.swing.JRadioButton rbNasiPadang;
    // End of variables declaration//GEN-END:variables
}
